"""
Markdown-to-PDF server — stdlib HTTP + markdown + fpdf2.

Zero frameworks. Uses:
  - http.server (stdlib)
  - markdown (pure Python, ~100KB)
  - fpdf2 (pure Python, ~300KB)

Run: cd python && uv run --package md-to-pdf python md-to-pdf/server.py
"""

import http.server
import json
import os
import re
import tempfile
from pathlib import Path

try:
    import markdown
    from fpdf import FPDF
except ImportError:
    print("[md-to-pdf] Missing deps. Run: uv sync")
    exit(1)

PORT = int(os.environ.get("MD2PDF_PORT", 8083))
OUTPUT_DIR = Path(__file__).parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True)


class PdfRenderer(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)
        self.add_font("dejavu", "", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", uni=True)
        self.add_font("dejavu", "B", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", uni=True)
        self.add_font("dejavu", "I", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf", uni=True)
        self.add_font("dejavu", "BI", "/usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf", uni=True)

    def header(self):
        if self.page_no() > 1:
            self.set_font("dejavu", "I", 8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 8, "Generated by md-to-pdf", align="R")
            self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("dejavu", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def write_markdown(self, md_text):
        html = markdown.markdown(md_text, extensions=["tables", "fenced_code", "codehilite"])
        self._write_html(html)

    def _write_html(self, html):
        # Strip HTML tags for simple text rendering
        text = re.sub(r'<br\s*/?>', '\n', html)
        text = re.sub(r'</(p|div|h[1-6]|li|tr)>', '\n', text)
        text = re.sub(r'<[^>]+>', '', text)
        text = text.replace('&amp;', '&').replace('&lt;', '<').replace('&gt;', '>').replace('&quot;', '"')

        lines = text.split('\n')
        for line in lines:
            line = line.strip()
            if not line:
                self.ln(4)
                continue

            # Detect headings by markdown pattern (since we stripped tags)
            if line.startswith('# '):
                self.set_font("dejavu", "B", 18)
                self.set_text_color(30, 30, 30)
                self.ln(6)
                self.multi_cell(0, 10, line[2:])
                self.ln(2)
            elif line.startswith('## '):
                self.set_font("dejavu", "B", 15)
                self.set_text_color(50, 50, 50)
                self.ln(4)
                self.multi_cell(0, 8, line[3:])
                self.ln(2)
            elif line.startswith('### '):
                self.set_font("dejavu", "B", 13)
                self.set_text_color(70, 70, 70)
                self.ln(3)
                self.multi_cell(0, 7, line[4:])
                self.ln(1)
            elif line.startswith('- ') or line.startswith('* '):
                self.set_font("dejavu", "", 11)
                self.set_text_color(40, 40, 40)
                self.cell(8)
                self.multi_cell(0, 6, f"  {line[2:]}")
            elif line.startswith('```'):
                continue
            else:
                self.set_font("dejavu", "", 11)
                self.set_text_color(40, 40, 40)
                self.multi_cell(0, 6, line)


def handle_convert(md_text, title="Document"):
    pdf = PdfRenderer()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_title(title)
    pdf.write_markdown(md_text)

    filename = f"doc_{hash(md_text) & 0xFFFFFF:06x}.pdf"
    filepath = OUTPUT_DIR / filename
    pdf.output(str(filepath))
    return {"ok": True, "file": filename, "path": str(filepath), "pages": pdf.page_no()}


class Handler(http.server.BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        print(f"[md-to-pdf] {args[0]}" if args else "")

    def _json(self, code, obj):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def _read_body(self):
        length = int(self.headers.get("Content-Length", 0))
        if length:
            return json.loads(self.rfile.read(length))
        return None

    def do_GET(self):
        if self.path == "/health":
            self._json(200, {"status": "ok"})
        elif self.path.startswith("/pdf/"):
            filename = self.path.split("/pdf/", 1)[1]
            filepath = OUTPUT_DIR / filename
            if not filepath.exists():
                self._json(404, {"error": "Not found"})
                return
            data = filepath.read_bytes()
            self.send_response(200)
            self.send_header("Content-Type", "application/pdf")
            self.send_header("Content-Length", str(len(data)))
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(data)
        else:
            self._json(404, {"error": "Not found"})

    def do_POST(self):
        body = self._read_body()
        if self.path == "/convert":
            md_text = (body or {}).get("markdown", "")
            title = (body or {}).get("title", "Document")
            if not md_text.strip():
                self._json(400, {"error": "Markdown is empty"})
                return
            try:
                self._json(200, handle_convert(md_text, title))
            except Exception as e:
                self._json(500, {"error": str(e)})
        else:
            self._json(404, {"error": "Not found"})

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()


if __name__ == "__main__":
    print("=" * 50)
    print("  Markdown-to-PDF (stdlib-only)")
    print("=" * 50)
    print(f"  Port:    {PORT}")
    print(f"  Engine:  markdown + fpdf2")
    print(f"  Output:  {OUTPUT_DIR}")
    print("=" * 50)

    server = http.server.HTTPServer(("0.0.0.0", PORT), Handler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down...")
        server.server_close()
